{
 "title": "Westworld 3.1 Analyzer",
 "time": { "from": "2020-11-23T18:17:46.791Z", "to": "2020-11-23T18:20:54.815Z" },
 "templating": {
  "list": [
   {
    "name": "peer",
    "query": "show tag values with key = \"peer\" where type =~ /westworld31/"
   }
  ]
 },
 "panels": [
  {
   "title": "Rx/Tx Bytes",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "250ms" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rx_bytes",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=~", "value": "/^$peer$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "250ms" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tx_bytes",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=~", "value": "/^$peer$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "250ms" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "retx_bytes",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=~", "value": "/^$peer$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "250ms" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dup_rx_bytes",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=~", "value": "/^$peer$/" }
     ]
    }
   ]
  },
  {
   "title": "Rx/Tx Messages",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "250ms" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rx_msgs",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=~", "value": "/^$peer$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "250ms" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tx_msgs",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=~", "value": "/^$peer$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "250ms" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "retx_msgs",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=~", "value": "/^$peer$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "250ms" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dup_rx_msgs",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=~", "value": "/^$peer$/" }
     ]
    }
   ]
  },
  {
   "title": "txPortal",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "250ms" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tx_portal_capacity",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=~", "value": "/^$peer$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "250ms" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tx_portal_sz",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=~", "value": "/^$peer$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "250ms" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tx_portal_rx_sz",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=~", "value": "/^$peer$/" }
     ]
    }
   ]
  },
  {
   "title": "rxPortal",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "250ms" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rx_portal_sz",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=~", "value": "/^$peer$/" }
     ]
    }
   ]
  },
  {
   "title": "retxMs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "250ms" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "retx_ms",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=~", "value": "/^$peer$/" }
     ]
    }
   ]
  },
  {
   "title": "dupAcks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "250ms" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dup_acks",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=~", "value": "/^$peer$/" }
     ]
    }
   ]
  },
  {
   "title": "retxScale",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "250ms" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "retx_scale",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=~", "value": "/^$peer$/" }
     ]
    }
   ]
  },
  {
   "title": "Allocations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "250ms" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "allocations",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=", "value": "${peer}" }
     ]
    }
   ]
  }
 ]
}