{
 "title": "Westworld2 Analyzer",
 "time": { "from": "2020-07-27T18:15:20.693Z", "to": "2020-07-27T18:15:43.361Z" },
 "panels": [
  {
   "title": "Peer 0 Rx/Tx",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "txBytes",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=", "value": "0" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rxBytes",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=", "value": "0" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "retxBytes",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=", "value": "0" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "duplicateRxBytes",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Peer 1 Rx/Tx",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "txBytes",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=", "value": "1" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rxBytes",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=", "value": "1" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "retxBytes",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=", "value": "1" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "duplicateRxBytes",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Peer 0 Portal Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "txPortalSz",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Peer 1 Portal Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "txPortalSz",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Peer 0 Duplicate Acks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "duplicateAcks",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Peer 1 Duplicate Acks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "duplicateAcks",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Peer 0 RTT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "retxMs",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Peer 1 RTT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "retxMs",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Peer 0 Allocations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "allocations",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Peer 1 Allocations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "allocations",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=", "value": "1" }
     ]
    }
   ]
  }
 ]
}