{
 "title": "Westworld 2.1 Analyzer",
 "time": { "from": "2020-10-08T19:37:56.491Z", "to": "2020-10-08T19:38:24.056Z" },
 "templating": {
  "list": [
   {
    "name": "peer",
    "query": "show tag values with key = \"peer\""
   }
  ]
 },
 "panels": [
  {
   "title": "Rx/Tx Bytes",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rxBytes",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=~", "value": "/^$peer$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "txBytes",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=~", "value": "/^$peer$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "retxBytes",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=~", "value": "/^$peer$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dupRxBytes",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=~", "value": "/^$peer$/" }
     ]
    }
   ]
  },
  {
   "title": "Rx/Tx Messages",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rxMsgs",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=~", "value": "/^$peer$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "txMsgs",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=~", "value": "/^$peer$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "retxMsgs",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=~", "value": "/^$peer$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dupRxMsgs",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=~", "value": "/^$peer$/" }
     ]
    }
   ]
  },
  {
   "title": "txPortal",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "txPortalCapacity",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=~", "value": "/^$peer$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "txPortalSz",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=~", "value": "/^$peer$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "txPortalRxSz",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=~", "value": "/^$peer$/" }
     ]
    }
   ]
  },
  {
   "title": "rxPortal",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rxPortalSz",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=~", "value": "/^$peer$/" }
     ]
    }
   ]
  },
  {
   "title": "RTT",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "retxMs",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=~", "value": "/^$peer$/" }
     ]
    }
   ]
  },
  {
   "title": "dupAcks",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dupAcks",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=~", "value": "/^$peer$/" }
     ]
    }
   ]
  },
  {
   "title": "Allocations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "allocations",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "peer", "operator": "=", "value": "${peer}" }
     ]
    }
   ]
  }
 ]
}