// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package westworld2

import "strconv"

type Type int8

const (
	TypeHELLO Type = 0
	TypeACK   Type = 1
	TypeDATA  Type = 2
	TypeCLOSE Type = 3
)

var EnumNamesType = map[Type]string{
	TypeHELLO: "HELLO",
	TypeACK:   "ACK",
	TypeDATA:  "DATA",
	TypeCLOSE: "CLOSE",
}

var EnumValuesType = map[string]Type{
	"HELLO": TypeHELLO,
	"ACK":   TypeACK,
	"DATA":  TypeDATA,
	"CLOSE": TypeCLOSE,
}

func (v Type) String() string {
	if s, ok := EnumNamesType[v]; ok {
		return s
	}
	return "Type(" + strconv.FormatInt(int64(v), 10) + ")"
}
